### ISSUE TITLE
Gutenberg support

### ISSUE THREAD

**Issue by Andreslav** [radkill/simple-lazy-load-videos#21]
Hi! Everything is fine on the frontend, but there is a problem in the editor: see the screenshot.

![изображение](https://user-images.githubusercontent.com/39444579/225094836-813070bb-19b5-4762-bfe5-bb80983388ab.png)

The problem is not related to the theme or plugins.

**Comment by radkill** [comment]
Hi! Thanks for the feedback.
Is it Classic Editor or Gutenberg?

I haven't tested the plugin for Gutenberg compatibility, so I'll do that in the coming days.

**Comment by Andreslav** [comment]
@radkill, this is the editor of Gutenberg. Thanks!

And thanks for the plugin, Valery!

**Comment by radkill** [comment]
@Andreslav I fixed it in version 1.0.0, just update and check it.
