### ISSUE TITLE
YouTube Videos beginning with a hyphen do not show preview image

### ISSUE THREAD

**Issue by DDmUSA** [radkill/simple-lazy-load-videos#22]
I am embedding thirteen videos onto a Wordpress-driven webpage using the correct shortcode.  Two of the videos have a video ID that begins with the hyphen character,  These videos do not appear on the page with their respective preview image.  I am seeing a stock gray blob.  I suspect the hyphen character is preventing the preview from appearing.  If I click on the play button, the video does load.

**Comment by DDmUSA** [comment]
Kindly disregard what I submitted.  I determined that I had two videos on YouTube that were set to "not made for kids", and perhaps it was this setting that prevented the preview image from loading correctly.

**Comment by radkill** [comment]
@DDmUSA Hey!
Thank you for your feedback.
Can you provide a link to one of these videos? I want to investigate this question just in case.

**Comment by radkill** [comment]
@DDmUSA ?
